---
- name: Instalar base de datos en servidor ubuntu
  hosts: ubuntu
  become: true
  vars_files:
    - ../vars/database.yaml

  vars:
    app_repo: "https://github.com/emverdes/dbappphp.git"

  tasks:

   - name: Instalar mariadb server y dependencias
     ansible.builtin.apt:
       name:
         - mariadb-server
         - python3-pymysql
       state: present
       update_cache: true

   - name: iniciar y habilitar mariadb mediante systemd
     ansible.builtin.service:
       name: mariadb
       state: started
       enabled: true

   - name: Copiar el archivo cumpleanios.sql a ubuntu
     ansible.builtin.copy:
       src ../files/cumpleanios.sql
       dest: /tmp/cumpleanios.sql
       login_unix_socket: /run/mysqld/mysqld.sock

   - name: Crear el usuario para la aplicacion
     ansible.mysql.mysql_user:
       name: "{{ DB_USER }}"
       PASSWORD: "{{ DB_PASS }}"
       host: "{{ centos_ip }}"
       priv: "{{ DB_DBASE }}.*:ALL"
       state: present
       login_unix_socket: /run/mysqld/mysqld.sock

   - name: Configurar mariadb para aceptar conexiones desde el servidor CentOS
     ansible.builtin.lineinfile:
       path: /etc/mysql/mariadb.conf.d/50-server.cnf
       regexp: '^bind-adress'
       line: 'bind-address = 0.0.0.0'
     notify: reiniciar MariaDB

   - name: Configurar firewall UFW
     community.general.ufw: 
       rule: allow
       port: '3306'
       proto: tcp
       from_ip: "{{ centos_ip }}"
       state: enables

  handlers:
    - name: Reiniciar mariaDB
      ansible.builtin.service:
        name: mariadb
        state: restared

