---
- name: Instalar y configurar mariadb en ubuntu
  hosts: ubuntu01
  become: true
  vars_files:
    - ../vars/database.yaml

  tasks:

  - name: Instalar maria db server
    ansible.builtin.apt:
      name: mariadb-server
      state: present
  
  -
